model:
  _target_: src.models.prototype_module.PrototypeModule
  train:
    exp_name: test
    sr: 22050
    seg_len: 0.2
    n_shot: 5
    k_way: 10
    device: cuda
    lr_rate: 0.001
    scheduler_gamma: 0.65
    scheduler_step_size: 10
    num_episodes: 2000
    adaptive_seg_len: true
    use_validation_first_5: true
    load_weight_from: null
    negative_train_contrast: true
    negative_seg_search: false
    merging_segment: false
    remove_long_segment: false
    padd_tail: false
  path:
    root_dir: /content/drive/MyDrive/TFM/task5/DCASE_2022_Task_5
    train_dir: /content/drive/MyDrive/TFM/task5/DCASE_2022_Task_5/Development_Set/Training_Set
    eval_dir: /content/drive/MyDrive/TFM/task5/DCASE_2022_Task_5/Development_Set/Validation_Set
    test_dir: null
    extra_train_dir: null
    mask_dir: null
  features:
    eps: 2.0e-16
    fmax: 11025
    fmin: 50
    sr: 22050
    n_fft: 1024
    n_mels: 128
    hop_mel: 256
    feature_types: pcen@delta_mfcc
    embedding_dim: 2048
    drop_rate: 0.1
    with_bias: false
    non_linearity: leaky_relu
    time_max_pool_dim: 4
    layer_4: false
    test_seglen_len_lim: 30
    test_hoplen_fenmu: 3
  eval:
    seg_len: 0.2
    hop_seg: 0.05
    samples_neg: 30
    iterations: 6
    query_batch_size: 8
    negative_set_batch_size: 16
    threshold: 0.9
    negative_estimate: freq_mask
  net:
    _target_: src.models.components.protonet.ResNet
    features:
      eps: 2.0e-16
      fmax: 11025
      fmin: 50
      sr: 22050
      n_fft: 1024
      n_mels: 128
      hop_mel: 256
      feature_types: pcen@delta_mfcc
      embedding_dim: 2048
      drop_rate: 0.1
      with_bias: false
      non_linearity: leaky_relu
      time_max_pool_dim: 4
      layer_4: false
      test_seglen_len_lim: 30
      test_hoplen_fenmu: 3
model/params/total: 724096
model/params/trainable: 724096
model/params/non_trainable: 0
datamodule:
  _target_: src.datamodules.prototype_datamodule.PrototypeDataModule
  data_dir: /content/drive/MyDrive/TFM/task5/DCASE_2022_Task_5/data/
  train_param:
    exp_name: test
    sr: 22050
    seg_len: 0.2
    n_shot: 5
    k_way: 10
    device: cuda
    lr_rate: 0.001
    scheduler_gamma: 0.65
    scheduler_step_size: 10
    num_episodes: 2000
    adaptive_seg_len: true
    use_validation_first_5: true
    load_weight_from: null
    negative_train_contrast: true
    negative_seg_search: false
    merging_segment: false
    remove_long_segment: false
    padd_tail: false
  eval_param:
    seg_len: 0.2
    hop_seg: 0.05
    samples_neg: 30
    iterations: 6
    query_batch_size: 8
    negative_set_batch_size: 16
    threshold: 0.9
    negative_estimate: freq_mask
  path:
    root_dir: /content/drive/MyDrive/TFM/task5/DCASE_2022_Task_5
    train_dir: /content/drive/MyDrive/TFM/task5/DCASE_2022_Task_5/Development_Set/Training_Set
    eval_dir: /content/drive/MyDrive/TFM/task5/DCASE_2022_Task_5/Development_Set/Validation_Set
    test_dir: null
    extra_train_dir: null
    mask_dir: null
  features:
    eps: 2.0e-16
    fmax: 11025
    fmin: 50
    sr: 22050
    n_fft: 1024
    n_mels: 128
    hop_mel: 256
    feature_types: pcen@delta_mfcc
    embedding_dim: 2048
    drop_rate: 0.1
    with_bias: false
    non_linearity: leaky_relu
    time_max_pool_dim: 4
    layer_4: false
    test_seglen_len_lim: 30
    test_hoplen_fenmu: 3
  batch_size: 64
  train_val_test_split:
  - 55000
  - 5000
  - 10000
  num_workers: 0
  pin_memory: false
trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: auto
  min_epochs: 1
  max_epochs: 200
  num_sanity_val_steps: 0
seed: 1234
callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val/acc
    mode: max
    save_top_k: 1
    save_last: true
    verbose: false
    dirpath: checkpoints/
    filename: epoch_{epoch:03d}_val_acc_{val/acc:.2f}
    auto_insert_metric_name: false
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: val/acc
    mode: max
    patience: 10
    min_delta: 0.0
  model_summary:
    _target_: pytorch_lightning.callbacks.RichModelSummary
    max_depth: -1
